<a href="https://colab.research.google.com/github/bryanf98/IA_2020B/blob/main/ANNvsSVM/SVM_Ingreso_De_Adultos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install mglearn

In [20]:
#Se define las librerias a utilizar
from sklearn.svm import SVC
from sklearn.decomposition import PCA
import pandas as pd #procesamiento de archi9vos 
import numpy as np
import matplotlib.pyplot as plt
import mglearn
from keras.models import Sequential
from keras.layers import Dense
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix  #matrix de confusion
from sklearn import preprocessing
from keras import optimizers
from sklearn.metrics import classification_report
from sklearn.preprocessing import minmax_scale
from google.colab import files

In [3]:
upload = files.upload()

Saving adult-training.csv to adult-training.csv


In [21]:
def leerData(ruta):
    df = pd.read_csv(ruta, sep=',')
    return df

def dibujar(errorRate,title):
    plt.figure(figsize=(15, 6))
    plt.plot(errorRate, color='blue', linestyle='dashed',
             marker='o', markerfacecolor='red', markersize=10)
    plt.xlabel('Número de K')
    plt.ylabel(title)
    plt.show()
    return

def clasificadorSVM(kernel, X,y):
    cls=SVC(kernel=kernel,gamma=10)
    cls.fit(X,y)
    cls.score(X,y)
    return cls

def resultadosSVM(cls, X, y):
    score = cls.score(X, y)
    return score

def predecirSVM(cls, X, y):
    yPred = cls.predict(X)
    matrixConf = confusion_matrix(y, yPred)
    report = classification_report(y, yPred)
    return matrixConf, report


In [52]:
upload2=files.upload()

Saving adult-test.csv to adult-test (2).csv


In [22]:
#Se lee los datos de entrenamiento y testeo
dataframe=leerData('adult-training.csv')

#dataframe=NormalizarData(dataframe)

**Encode en las categorias de la data de entrenamiento:**

In [23]:
from sklearn.preprocessing import LabelEncoder 

caracteristicas=[x for x in dataframe.columns if dataframe[x].dtype=="object"]

le=LabelEncoder()

for col in caracteristicas:
    if col in dataframe.columns:
        i = dataframe.columns.get_loc(col)
        dataframe.iloc[:,i] = dataframe.apply(lambda i:le.fit_transform(i.astype(str)), axis=0, result_type='expand')




In [24]:
X_train = dataframe.values[:,:-1]
X_train = minmax_scale(X_train)
y_train=dataframe.iloc[:,-1].values

**Leemos laS data del testeo:**

In [25]:
dataframe=leerData('adult-test (2).csv')


**Encode en la data del testeo:**

In [26]:
from sklearn.preprocessing import LabelEncoder 

caracteristicas=[x for x in dataframe.columns if dataframe[x].dtype=="object"]

le=LabelEncoder()

for col in caracteristicas:
    if col in dataframe.columns:
        i = dataframe.columns.get_loc(col)
        dataframe.iloc[:,i] = dataframe.apply(lambda i:le.fit_transform(i.astype(str)), axis=0, result_type='expand')

In [27]:
X_test = dataframe.values[:,:-1]
X_test = minmax_scale(X_test)
y_test= dataframe.iloc[:,-1].values
#print(dataframe)

In [28]:
## Se concatena los datos de X_train y X_test para enviar al clasificador 
x=np.concatenate((X_train,X_test), axis=0)
y=np.concatenate((y_train,y_test), axis=0)

In [12]:
from sklearn.svm import SVC

** Se realiza el modelo SVC**

In [29]:
## Se ejecuta el clafificador para generar el modelo
cls=SVC(kernel="rbf",gamma=10)
cls.fit(x,y)
cls.score(x,y)

0.8728910728910729

**Accuracy entrenamiento y testeo**

In [30]:
##Se obtiene y se imprime medidas de Rendimiento
score_Train=resultadosSVM(cls,X_train,y_train)
print(round(score_Train,4))
score_Test=resultadosSVM(cls,X_test,y_test)
print(round(score_Test,4))


0.8732
0.8724


In [31]:
##Seobtiene y se imprime la matrices de confusion
matrix_conf, report =predecirSVM(cls,X_train,y_train)
print(matrix_conf)
print(report)
matrix_conf, report =predecirSVM(cls,X_test,y_test)
print(matrix_conf)
print(report)

[[23428  1291]
 [ 2839  5002]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92     24719
           1       0.79      0.64      0.71      7841

    accuracy                           0.87     32560
   macro avg       0.84      0.79      0.81     32560
weighted avg       0.87      0.87      0.87     32560

[[11785   649]
 [ 1429  2417]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92     12434
           1       0.79      0.63      0.70      3846

    accuracy                           0.87     16280
   macro avg       0.84      0.79      0.81     16280
weighted avg       0.87      0.87      0.87     16280



**Predicción:**

In [32]:
valPredict_train=cls.predict(X_train).round()
confusion_matrix_train=confusion_matrix(y_train,valPredict_train)
valPredict_test=cls.predict(X_test).round()
confusion_matrix_test=confusion_matrix(y_test,valPredict_test)

**Matriz de confusión:**

In [33]:
print("===============Matriz de confusión entrenamiento===============")
print(confusion_matrix_train)
print("==============Matriz de confusión testeo================")
print(confusion_matrix_test)

===============Matriz de confusión entrenamiento===============
[[23428  1291]
 [ 2839  5002]]
==============Matriz de confusión testeo================
[[11785   649]
 [ 1429  2417]]


In [34]:
print("-Entrenamiento: ",round(score_Train,4))
print("-Testeo: ",round(score_Test,4))

-Entrenamiento:  0.8732
-Testeo:  0.8724
